language: node_js
node_js:
- stable
sudo: false
script:
- npm run build
before_install:
- openssl aes-256-cbc -K $encrypted_8f92be6076c3_key -iv $encrypted_8f92be6076c3_iv
  -in id_rsa.enc -out id_rsa -d
