language: node_js
addons:
  ssh_known_hosts: 123.207.14.113
  apt:
    packages:
    - sshpass
node_js:
- stable
sudo: false
script:
- npm run build
before_install:
- openssl aes-256-cbc -K $encrypted_93414c0ea4e4_key -iv $encrypted_93414c0ea4e4_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 123.207.14.113\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- export SSHPASS=$pwd
- zip -r app.zip ./dist
- sshpass -e ssh travis@102.201.64.94 'rm -rf /usr/local/source/distss/deploy.sh' 
- sshpass -e ssh travis@102.201.64.94 'rm -rf /usr/local/source/distss/app.zip' 
- sshpass -e scp ./app.zip travis@123.207.14.113:/usr/local/source/distss/
- sshpass -e scp ./deploy.sh travis@123.207.14.113:~/
- sshpass -e ssh travis@102.201.64.94 'sh /usr/local/source/distss/deploy.sh' 
env:
  global:
  - secure: do0JplNeBZQIKk4uWZEqKsKGdO1hDnPkgKNBiZEZrBZIqJQoB89LzyuUT8Jd+Fm39aKoGz//d8lMmmBALmNMHPKcpiY4Y1Y/1YwmtwzqwbWUswXDXwJqyePVd9OxAGRb5irW20e+34WMXZukOPcDV3JmacEM0DQwp1NYyQUc15vxO44JUcU/R/mF1k0+QsI04a7Ydp875uHcgHzbANSgOOJbDeDZgyLnFqGftknwRrv6TeXcOmcIEOY1FrU/ia5uRrOlnHbTVt26T7UtzFbv1RZmlAqsSHTRIKiwohCXuOPUjJ4vDsAoEkVUQ9jb09przPXGCbphmPbhn0Wac3g5F+DhH5NJQnGGzDj7Vzl9VQK7ILSeg9BvRSwYUgm5IFwmxfvbIc1zxC61wFPxJNiAghhVSflnnsyZc6V38QVyN3WnIG5Dz8WNzzhCizSFV0h2b25FRO3JEl729ZSgRooWdkfLsXvevOZ6MQxYHsmbJ7F+z0S6d+LHkApouLp7pcfLiOSsYpu/0N0ic8w9QC5+WhsAxbGm1DeKqAch/sezlqKnmR8t+7mPP4+lR2VOFENT8qjF9W0E1RIT4FQtVAf9qCFhSUnzrX097ulZJ+xi3Gwho9iWsCHHu7dNMyngyz6Pv0M+mKAIMIlaUcWz3vZJBU+WQ0iyfYjRzRNxj6d1ZKo=
  - secure: WVVTQIneJOzLw5S+L+7bXWUln/Tut43XFmRM5oZFCGIREuZRzSXsnxByJqR6v0FzX2V5h5uHo70D+96w73KuYBNRQnrFCTv0TUiM9C7kwNbnjJGx08IYN3r0b89d0oKv+xSCeClRtRvVYJlWohh1Ho+xGoUg4z5igahbbAyWMUh4sBIoA+TiGmYQPgBTDP075BrECzs89PmlHzzJS/AQlzcmQNECGltrYYiI86a/Rfr3h8niqyI5++zsdk4lbkiptVmsMzMLGAoHU6vd6PX7NMTMMgzNeyJMHzzaei5foQvk0qf1+WpmSB8e/VdmCxYQD6HjS9Pf18fYs5loU6FmXnHEKDBZtgnuginkXEv7/ZJ1cW8eWQCyFMVCWjuocs/uS4oCga7qo0i5yE1LDDtPu+XKgpSaeT9HAgjdKIFWMk9YZHq15RaGYuo/OR6ZUBV2HZsDfE5Yai1MCGldgP9DEjndmVb9VesjPIG7xIhj3bxvr1uKLU120b6nwCYqJu8uDOUUABZ0VueYqcA4ridsPKKGZakbo1jtMTU8+saNieF1KuVOAv82yoNN7kM4W0uR5jGlStpD66fo2iXs8YoilIFE7reg1AdqlincAwsGHs3ipf1PJcxpQv0DLVsR3H29y4j5x3GNMWu6NKk8oDj3gPHQOYgYhLQG5Dt5LSezBEc=