language: node_js
addons:
  ssh_known_hosts: 123.207.14.113
  apt:
    packages:
    - sshpass
node_js:
- stable
sudo: false
script:
- npm run build
after_success:
- export SSHPASS=$pwd
before_install:
- openssl aes-256-cbc -K $encrypted_93414c0ea4e4_key -iv $encrypted_93414c0ea4e4_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 123.207.14.113\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- zip -r app.zip ./dist
- sshpass -p $pwd scp ./app.zip $uid@123.207.14.113:/usr/local/source/distss/
- sshpass -p $pwd scp ./deploy.sh $uid@123.207.14.113:/usr/local/source/distss/
- sshpass -p $pwd $uid@123.207.14.113 "sh /usr/local/source/distss/deploy.sh"
env:
  global:
  - secure: CuSQEn9f16fzmds50hfbAB5cB1EjS/KqOsRFDGjA6cK+uLEvpOjBcgVksk8a5FaizsHdH4UiVF2LYV/JD0O7hGMfmqWJGAwFk4x3yV8TUaEfSPNdl0gHwCaqDiL2c4uWUWJoFdJDVzRNelOMIMWAdE7hqjLpUVLGYPWvpytU4DuTRIevZ7we6wfJ19osmCaiXtzgsBqBmZHeDj9aGdj57paQZrvWTAFKOQhzoojSS0TcAf6Z69zhNfp8j3n2a0zPTIkdQBPCgPGcBbdx60mUnxO0uEK/o6+VnnR8abwZdhuAZv7qDYJiQhuhjDxXrOFPfxBubBMebS3tuKa1HmLTDPhWo3KSnFGUSCAgX3diODjjZ8BaraHraU6pXsGq9jWxmw4wjrr1Omj2OG3S9IYMCCQTsBt0zlR9mU8ueJI2hSWSbeZInbvclW3EI32dFo5njePyAqPQJiAXAHecMp9RhKGWBYfWnVitkGZI8hiccR00rn3mE03zxXoGAlA2uaZnHZhLjjfkGTRtLcqnpurtsAiEe3El6RSbI3OKoYZQSIpAhNqPCl023eisU2Ag/+jegVrFO2u3gyOyq6EmuCkAWYc6WNFCVVg5W3JIWuDPs9ujjzKvM4TIqpm2KG8nLGm+X4xgrOWabYN3zfVQ9/yJsadQCpNuaAfUQlabOgRpwdg=
  - secure: CESJ+POeJT/lklYj3WGc8E3kjGyW92jNQTqBAP5PEmY8FET0uylAZ0AMcg8uV5Dm6WdoKSF3P2KTNR6kiGh026GJCAj7b9mJvtAYGA6Tq2n75gcvJBCRgbHfby4Ygs/ok98rUyGyUu27V48lxqZDOUbVRP/nmZADSjuxWcx5Q1OA5Ia9pguwiNQhRZARdICglfQPTJ61kVzjLqKMJS9M/Py5OPE3Lq87yUCkgl2Ft5DM2/y4MRbJTIDXnWUpaAYAxI33DVeW41DD3PBQT0I92rGJB9GB8af/Wd8j1k/+Ll9n0lA4z6MzCt7nOVzhsx8yZCtZJ4/hNKZmKqMpY8yNYSLNwAOGERN04IxbFFyMc2wJpPEwtftIbScgA+nSWJbdnEAsP9EB4os+z4/UG/Nv7u4xib2UVOLRAJqHj6Wdkh3Hi0wiDCOz6g7AT4a8HjuWnN/q2pTPOEE/7hegAZHD7RegFxyDH5VxCohDTi6/CS/tQmTUMUcGC/+9TrZd0fRq4q34OgTzcm4vC3YcZrIQKE0tlqoghgBnVKViUEBUg0ZJ0D2eXQIk0n9NWlVHyvXH4G2GgxXkQ2l+SHvnsJkBpxh89kfyr4bhJko2IXWLp4MxjjsAMs/7LZFhDGvosCT4EDpZQMOTfFsuZlRGADg7bUEBqOnfO5I2zOfRDxNLuuA=
