language: node_js
node_js:
- stable
sudo: false
script:
- npm run build
before_install:
- openssl aes-256-cbc -K $encrypted_93414c0ea4e4_key -iv $encrypted_93414c0ea4e4_iv
  -in bowencrm_id_rsa.enc -out ../bowencrm_id_rsa -d
deploy
scp ./disp root@123.207.14.113:/usr/local/source/crm/app

