language: node_js
addons:
  ssh_known_hosts: 123.207.14.113
  apt:
    packages:
    - sshpass
node_js:
- stable
sudo: false
script:
- npm run build
before_install:
- openssl aes-256-cbc -K $encrypted_93414c0ea4e4_key -iv $encrypted_93414c0ea4e4_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 123.207.14.113\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- export SSHPASS=$pwd
- zip -r app.zip ./dist
- sshpass -e scp -P $port ./app.zip $host:/usr/local/source/distss/
- sshpass -e scp -P $port ./deploy.sh $host:/usr/local/source/distss/
- sshpass -e ssh -p $host $host 'cd /usr/local/source/distss && sh deploy.sh'
env:
  global:
  - secure: JS7UryrcNBtHLzIi0djb0j0qvifSjXZ9uBG22aQolNYeKXNj+dnvwVAr/dWHpIfJaFG3dtFlu9Vju5i30wRr5x/5/GxoC6UdiqXim3NPPViMnVxFuLl3lfQRpD/VEX8M1aq2jlRqNHn/JnPEihAbEAAIltZFgPs+/Pk1FPAnBIVzcN+kM/xOB7C4q+P7HjOLg8ZrKs3g06HpjkCwf6AFcd0GOJ89Z7tUslNywSuETc/pthqow2L7byIN/9M6Z9soRqPFeGZw6JaTOIi2Sp1ExaeEq72Oz9bh+umHOKEJFT574NW72LsO/I9jCVpj+LIV0q6kqk+JKd33HnkO/H7VU0rzdMWFqJcVOe5vefYVN5pjAUN96i9CCEX9N64QOXZpW5vdmVsgb7NY/vdp/gj8AvMGWtcEA5os4/59sd2Qf4XeUhtZQWHYdPwKEw8uHxglwaDyE+F446tuHu+9LSqMP2jbWyf5/sW+/CKcsNDJHIYR3tB94LGFwgblNGfiF/ahSSkwhdO2fznA7xqFEH5wasvI3w/1tbynC3C8MyUZNuJCFVVs8m9yp3d4MBwv1vnJS1BFndZTqwB30vJOoWCXHZ03pHRkjGEUyTucZ2h24MpTB0ZCUOGlrNu1Xj93Wzvt+ygLGUbvbfplQgb/lnwYQ3Wb78icdsQAj92tvlq7aDg=
  - secure: ZvBl2GNqrj7I35JXrf4USGNa86GjnjkoxrzT2aakPhjCnB+5nISMj783Coq2QkfJ4PJI1nVclE47Irk4xJkZdCyECaJFDdUCGPULYmSJs8eRLPYjj5IGl7EUS+OAjHn8nc/A/Dcv48YrOrfX6pBV8cCpNw6qBSvwL3szyNoYgws70pyZuMAD0qDTl89ODs25GC16pTFfRXFVIH9oNbroyRoWswhGNEbojWZIk7ekO4twLl3qInssw7dt1q+olklvs8pJYjvlKvNxVhhURK/FhsQrjf+vc8K4WMi2Za7nhLpkkYZsitnVNhG9UCVOFwW2zKeu/1VYVcgBF9XGvigxdexIPMa0GX+zK9lBjgNNbX85b7hUMPn1eAtox5ZhWCCCkelYVAbX+VbBfntZBB57IEtXNTNk2Nr8oYLlJTqP04MXKQeXR7vQV96JxSLGNrAbCRYZqRstg/bJdC3Bu5IQ5piNGsya2xhZwuQUdBJK/AcFdolyZyE8JeQqfeqslvwOVDMg1BD5KjnlitRZUiDLXEWNprgIfbPQq3NCB9Cvlo6nhGIoM2kNNWq9JvJd+UISB5XH4sp54FWWZ9L/1nEEM1likvzwFHlfwN1VEumdoErDhkNowpFOacUnRw48vsO9hJYwj2SXBewpDBzBlySRyJ6J/H6VmpJMSbG7HODrGOY=
  - secure: FkQ4suSBNCUZmmVv6Rmtp3n0n8Cc29Vg21Qkg90ZmNGCLacc155ISSdw37OOACfEH9IpW44SzlRL1r8G+D3QpHwDa4BlAK4CYI9nD0bhrT2IoZcthpbRftiVpRACHNG++B5TvKlOQfYU32b2UIM/dRwwhrpcVUo7LvilxaX2i63gDxTvT9UYBhTvT9thw87KYvsgLfM77bCI0CZIxvp+d7OYd4FWmH+cIFJBF4kEURN6jOUUSb4IifBkz56SZACyHHotoLuOUZTFxbhxx+j6ZZGep8zV2oNSYxk8KYasq5Cpg+Q2Sy8LEK/rhV0XP1/XWlLdf1SBA2iA8AUGvr2BXSgSfW7/3O3OS8LGYaUJ0/8sXJqPiFGLX/BY5G5PnX9tAiKlENjO+a02yKgNua2RzxJ+KpjQ8egFb2/W0MyXq5tptEfxx8ZSpLReHGPec9ZxtWlCXaa1AFg3Y6yleQDl2z71Qm0+OR2ORUydxy4mzNI7WAHlf9KvockYvpa079aqlodMu/Ng4fPS/6QNlPhGeNv1ZBGqaUuQy9HUOtEKlMMgRw4DT6g7nBAg34t+avUJCZy5dTdfd8UzZYtEAd5X1meOHMytA91ZcW6Gup85p11LMHguASbCxtoB4/tek4VbG5IzpuHH6pLhbafil+ESXPrBSKvsZLk7Mbnyq0NmzzY=
