language: node_js
node_js:
- stable
sudo: false
script:
- npm run build
before_install:
- openssl aes-256-cbc -K $encrypted_93414c0ea4e4_key -iv $encrypted_93414c0ea4e4_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 102.201.64.94\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- export SSHPASS=$DEPLOY_PASS
- sshpass -e scp -o stricthostkeychecking=no -r ./dist/* $DEPLOY_USER@123.207.14.113:~/.ssh/dist/

env:
  global:
  - secure: DSgCSLTS1AKps/AhGRN1xOvMT+cYow4YfdWHdWfK9geXMosPO7hv/H6MfJNmH+OX32j/wBBb3LShBoFwDt6vQFiaugOHbtHT/jIqt+fAwIQBhf5Y+9HrCHmVdK480/G5O3/tSi++MaRdtQDCrHUBOPLUN8p2rFeXrE830WrDwvrj6cYnJkUHSD5WBJfAavKUfKWKSs9LvNUIDEu/9KRmd+kHvbKAn0ri3TH6MaLSx8ACou8CfPvB9zi/UuqLl3DJuHEI3rUJ3mqHv9Chtj+e0S9srUG0NPnPY3+ig1OAIvmnZiaTIOGj+Ve6L4i+JYd122HWm2w2Kxg0cpkxMl50Qi1DMRbhhm6lm9LJf+blqL7bxJYvMpOynRUcd0TZap06u4y2JTRP/qHb80Z2Pje48zuGC7/ToYl6hoPpSr1TjoO0EPjXgzgwPJq2pciLSz2eWI9uIyuUmeqAk4GQHstTpx02SWLHuHrfTn9K4XAmUKmB7Td/rGfrNL6WNDe/HbqVUY/bGPvc7kQQ2aX+Vqo9AXLHnVyXfbK5T8lniT8ZvB5ctxXXmcUbD0HSpAhot/18B/UQbSn7rZjDBpcBl3hih8M9DaxsK0MtxglWu3QZ7gxVWs1A9vjzgLGvbHHvD/8ZOEUZVHGVxJlmXRfusQmJS5QIuq3JNOOym8U88DhJ0q4=
  - secure: RNX2oIo5JUUTwz2js+8A1+lCuvawYVShElpersJw8gogcC2rawyqJkJhFoACtuWGFKkQTqBkmEK0cN2+h2yl86c8Ah+h8XeB8CkKDSKd4juHWFnES0uZeb6o+N0x6mahlQ290Mo5ELrmchmFmzNQYexGpHKov2mmmOyFohRcwXr2fG+rjQOKxgrK56Mcn3A/LVCqaqGO3XdiSC7TwxA7ziR2zZo/DQe7z48ORJIMrHzERC8hw4pioqKxWHPJ4VUvJ9brrpa6gZXmzSQRvQ/jxtnpb06zFZm0MS1RcxR43DcZG7XHdGpo5UZ4VBRmCE931T23L7ZpBBEnFu4bBS8aQgHIaP6OfIMF1agHNDOWLXxIilzSXfCkju9g7zy9fTiaYb20b6Mbp65or1lpRX/bQtpwcr88USKTq9NLNtP9Zy7gemH2uw1X/x6/1WioeftOirwfUrF3BZULn8Pnb/vQiwPBMlWZYOiShYBGaz2ZvL6t3OvoN+TupitYTiCvQH3tfb4fYvKphfW70H6hkfAvAsHej1KDyC7ryYJbLL7YW0DvsIpwT++SXImcofk4E21ir3NPa6wXopdxw4OeN2wVDgu71G5TLh72oHsyYUZpob+GG61l8GE0Coy5QiHXUP3/wLEOo2Ia4WuV2DDHuRnSTrjI4mGWDZI7R50f2F22/jA=
