language: node_js
node_js:
- stable
sudo: false
script:
- npm run build
before_install:
- openssl aes-256-cbc -K $encrypted_93414c0ea4e4_key -iv $encrypted_93414c0ea4e4_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 123.207.14.113\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- sshpass -p $pwd scp ./dist/* $uid@123.207.14.113:/usr/local/source/distss/
env:
  global:
  - secure: Vf4iSq/oycSp/TcqPjhEPdIG0DY8x89AFKBxDtbm02mzrY5gkr+qJXHEwyYNFRCR0btBvrFsqeBUzGAXuB6prQsZibywEUIurT6/yKgkOBCig3QtOngspU+IvjavwG7HeqKMn9eucErCKJa3ogalH09WhhJfRm9eiI+LFh1Ku21oDxPGMK0ony2950Bo7yjBhH4V8EWiHCKAbOAf0pkSJ167NoWw5X/gG+400VxHoeivAL2GAuJ82QB0Zb7IInOh7PwKYyf8tkD676NXzYblyAiZrEpmFdIY8A3/e6W5cViooCsP5GgASfaKj3jRrrAuPu0Tr/FboVB3p0G7ke9CDzT41UUEI+aOhnjPWsvUki/Hk4jGpCzkwOtq23a6Q4nK3j+RcUd8GXtDZm+G2C5i8jpP5nSTLkgPUxMyldYrW/HFOn7/iwwDELYeyELygPecZD4fQFWY7Rrl+NPyAFRDl3muvTpDB86RwOMhJm7igiKAXwg/DAvfKM0xUWXNBdHbmgVAdOYge9vktl28L2eqO2GMU3K+gveSKuy+WjCZ8FLtz85NQWe31vT3re4iA4uV4m5FlfcyZ41om4wuxUC4JhR28oVUJee0TgVxP3e6fD2yEKIoTRwpJh7fFCu8OWhCNDI3BIHQHLbxum3IoSlgrFRKpDjEofCqFibD8hyCxoI=
  - secure: lUL9Am+w2B+EXm+rTh0iecYQGdlDEKuQp6+xKSBj2VpU6nd84g//+W3KbIf2T1DAatsrGFyAjszYTjAOAJ2wADMVTeGdaRdoCKNjrMB1J/2enlZsLQ1mChi9ZbD9yZyixAPPvYhTGKKgkdS6z41tx2W0OFCNLAsekt5DI0Dt5prtzyJdcoTaXNTzpqmBqUJk50/fqUtbPgzNwAahVWZraNWlkOY6G8aVXP9FoODARo4IyMNRJCe+9WWEFZKgoriK+JIjbogzvyZc7S0mwIHyWiIoM8hp7lhZ0L/GiR9biwDKq2SoAOs7iWHin5q4b9xwGgbJeIdKPivQDRNQQu3ISP3msiUdGlOWw4CpilsBh3lKsRj0I3h/+o6NJ9ssxvrIsT6a5OTHzNPNlqSXqw73VX1xdEBUqyKKMWErLuhuDzV8Ganc0/y5jAXgiTnnj7ynOsWr9fpKoBE+KpEtgKfun8vBKnBGAOJhHFcOnU1iISYKy/nYJHGGui0yuaUNS/JgY/iYfzj+nAvHpmUlp7//F2KhjAXffG6yeUUdXsu6/Jc/GXv3Dld50eGMPBV0Q3+2cTd9jjdrTgyKKSFCMZTycqB4AiKQhtrFpH1Nc00KxunFKXa3qVk2J8a4hG4sA1F2mV7DOQ/yr3HWZf7PeeljtDSaAFwlMqy0yS4Z6mndbSc=
